### ISSUE TITLE
Transaction is always pending, it should change if successful or failed

### ISSUE THREAD

**Issue by perminder-klair** [dexlab-io/dexpay-pos#155]

**Comment by perminder-klair** [comment]
fixed failing issue, please test @dimarconicola

**Comment by dimarconicola** [comment]
@perminder-klair @Alexintosh 
I still see it pending

<img width="709" alt="Screenshot 2019-05-08 at 12 28 59" src="https://user-images.githubusercontent.com/10923247/57369024-e4d47600-718c-11e9-8df5-d6562f06f3b8.png">

**Comment by Alexintosh** [comment]
Did you tried with a new one?

**Comment by dimarconicola** [comment]
I just wanted to but when I generate a bill, it shows a blank page
